export default {
    CHANGE_HOUR: 'CHANGE_HOUR',
    CHANGE_MINUTE: 'CHANGE_MINUTE',
    CHANGE_RING_TONE: 'CHANGE_RING_TONE',
    CANCEL_PRESS: 'CANCEL_PRESS',
    START_PRESS: 'START_PRESS',
    PAUSE_PRESS: 'PAUSE_PRESS',
};
